export const date: string;
export const image: string;
export const more: string;
export const post: string;
export const postList: string;
export const postTitle: string;
export const root: string;
export const title: string;
export const unPublish: string;
